"""Descrizione della migrazione

Revision ID: 099af553555b
Revises: 59cd61f9592b
Create Date: 2024-09-19 06:19:04.332306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099af553555b'
down_revision = '59cd61f9592b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
