"""Descrizione delle modifiche

Revision ID: 59cd61f9592b
Revises: 
Create Date: 2024-09-19 02:31:44.455545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cd61f9592b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_chats_name'), 'chats', ['name'], unique=True)
    op.create_index(op.f('ix_chats_uuid'), 'chats', ['uuid'], unique=False)
    op.create_table('patents',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_patents_uuid'), 'patents', ['uuid'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patents_uuid'), table_name='patents')
    op.drop_table('patents')
    op.drop_index(op.f('ix_chats_uuid'), table_name='chats')
    op.drop_index(op.f('ix_chats_name'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
