"""Descrizione

Revision ID: 86cf27cb5361
Revises: 099af553555b
Create Date: 2024-09-19 06:20:07.782962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cf27cb5361'
down_revision = '099af553555b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
