"""initial

Revision ID: e491b6b7b720
Revises: 
Create Date: 2024-09-19 08:47:06.265275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e491b6b7b720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id_', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_chats_id_'), 'chats', ['id_'], unique=False)
    op.create_index(op.f('ix_chats_name'), 'chats', ['name'], unique=True)
    op.create_table('patents',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_patents_uuid'), 'patents', ['uuid'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('messages',
    sa.Column('id_', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('chat_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chat_uuid'], ['chats.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_index(op.f('ix_messages_id_'), 'messages', ['id_'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id_'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patents_uuid'), table_name='patents')
    op.drop_table('patents')
    op.drop_index(op.f('ix_chats_name'), table_name='chats')
    op.drop_index(op.f('ix_chats_id_'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
